### ISSUE TITLE
Updating gateway config by timeout not working?

### ISSUE THREAD

**Issue by ohmycto** [graphql-services/graphql-gateway#24]
Hi there,

I'm trying to set up a gateway config update by a timeout passing `GRAPHQL_UPDATE_GATEWAY` and `GRAPHQL_UPDATE_GATEWAY_INTERVAL_MS` env vars. But I get the following exception:
```
app_1  | TypeError: Cannot read property 'load' of undefined
app_1  |     at getApolloServer (/code/apollo.js:25:46)
app_1  |     at Timeout.setInterval (/code/apollo.js:65:30)
app_1  |     at Timeout._onTimeout (/code/node_modules/async-listener/glue.js:188:31)
app_1  |     at ontimeout (timers.js:475:11)
app_1  |     at tryOnTimeout (timers.js:310:5)
app_1  |     at Timer.listOnTimeout (timers.js:270:5)
```
It looks like we should pass a gateway to `getApolloServer` [here](https://github.com/graphql-services/graphql-gateway/blob/master/apollo.js#L65). I'm not sure how to fix this properly, because a straightforward fix like this:
```node
const server = await getApolloServer(gateway, lambdaEnvironment);
```
causes errors from Prometheus:
```
app_1  | Error: A metric with the name graphql_queries_parsed has already been registered.
app_1  |     at Registry.registerMetric (/code/node_modules/prom-client/lib/registry.js:76:10)
app_1  |     at Counter.config.registers.forEach.registryInstance (/code/node_modules/prom-client/lib/counter.js:64:21)
app_1  |     at Array.forEach (<anonymous>)
app_1  |     at new Counter (/code/node_modules/prom-client/lib/counter.js:63:20)
app_1  |     at createMetricsPlugin (/code/node_modules/apollo-metrics/lib/index.js:10:20)
app_1  |     at getApolloServer (/code/apollo.js:27:31)
app_1  |     at <anonymous>
app_1  |     at process._tickDomainCallback (internal/process/next_tick.js:228:7)
app_1  |     at process.fallback (/code/node_modules/async-listener/index.js:565:15)
```

Could you help me with this? Thanks in advance!

**Comment by BeiZero** [comment]
Hi, I also move metrics creation on the top level #26  and it's work. But I'm not JS developer and maybe this fix terrible :)
